### ISSUE TITLE
Add a recurring Action to refresh data and redeploy

### ISSUE THREAD

**Issue by ezekg** [ezekg/fss.cool#2]
Tired of manually doing it. GitHub supports a cron schedule, iirc:

```yml
on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *' # midnight every day
```
